[project]
name = "travelnusa-app"
version = "0.1.0"
description = "TravelNusa FastAPI Backend"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-multipart",
    "jinja2"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["api", "backend"]
